### ISSUE TITLE
No Settings Page?

### ISSUE THREAD

**Issue by pioto** [d4rkr00t/linter-doiuse#2]
The documentation suggests that there should be a settings page for this plugin, to determine which browsers should be targeted. But I don't see any? I'm using Atom 0.209.0.

**Comment by d4rkr00t** [comment]
Hi, sorry for long wait. Have you tried to reinstall plugin. Because I have tried twice on clear atom installation on two different laptops and it works fine.

**Comment by pioto** [comment]
Hm, perhaps it was an issue in an older version of Atom or something. I can see the settings again, too, in Atom 0.211.0.

**Comment by d4rkr00t** [comment]
Ok, great!
